export interface StateData {
  slug: string;
  name: string;
  abbreviation: string;
  hasIncomeTax: boolean;
  incomeTaxRate: number;
  incomeTaxNote: string;
}

export const stateData: StateData[] = [
  {
    slug: "alabama",
    name: "Alabama",
    abbreviation: "AL",
    hasIncomeTax: true,
    incomeTaxRate: 5.0,
    incomeTaxNote: "flat rate of 5%",
  },
  {
    slug: "alaska",
    name: "Alaska",
    abbreviation: "AK",
    hasIncomeTax: false,
    incomeTaxRate: 0,
    incomeTaxNote: "no state income tax",
  },
  {
    slug: "arizona",
    name: "Arizona",
    abbreviation: "AZ",
    hasIncomeTax: true,
    incomeTaxRate: 2.5,
    incomeTaxNote: "flat rate of 2.5%",
  },
  {
    slug: "arkansas",
    name: "Arkansas",
    abbreviation: "AR",
    hasIncomeTax: true,
    incomeTaxRate: 4.7,
    incomeTaxNote: "top rate of 4.7%",
  },
  {
    slug: "california",
    name: "California",
    abbreviation: "CA",
    hasIncomeTax: true,
    incomeTaxRate: 13.3,
    incomeTaxNote: "progressive 1%-13.3%",
  },
  {
    slug: "colorado",
    name: "Colorado",
    abbreviation: "CO",
    hasIncomeTax: true,
    incomeTaxRate: 4.4,
    incomeTaxNote: "flat rate of 4.4%",
  },
  {
    slug: "connecticut",
    name: "Connecticut",
    abbreviation: "CT",
    hasIncomeTax: true,
    incomeTaxRate: 6.99,
    incomeTaxNote: "progressive 3%-6.99%",
  },
  {
    slug: "delaware",
    name: "Delaware",
    abbreviation: "DE",
    hasIncomeTax: true,
    incomeTaxRate: 6.6,
    incomeTaxNote: "progressive 2.2%-6.6%",
  },
  {
    slug: "florida",
    name: "Florida",
    abbreviation: "FL",
    hasIncomeTax: false,
    incomeTaxRate: 0,
    incomeTaxNote: "no state income tax",
  },
  {
    slug: "georgia",
    name: "Georgia",
    abbreviation: "GA",
    hasIncomeTax: true,
    incomeTaxRate: 5.49,
    incomeTaxNote: "flat rate of 5.49%",
  },
  {
    slug: "hawaii",
    name: "Hawaii",
    abbreviation: "HI",
    hasIncomeTax: true,
    incomeTaxRate: 11.0,
    incomeTaxNote: "progressive 1.4%-11%",
  },
  {
    slug: "idaho",
    name: "Idaho",
    abbreviation: "ID",
    hasIncomeTax: true,
    incomeTaxRate: 5.8,
    incomeTaxNote: "progressive 1%-5.8%",
  },
  {
    slug: "illinois",
    name: "Illinois",
    abbreviation: "IL",
    hasIncomeTax: true,
    incomeTaxRate: 4.95,
    incomeTaxNote: "flat rate of 4.95%",
  },
  {
    slug: "indiana",
    name: "Indiana",
    abbreviation: "IN",
    hasIncomeTax: true,
    incomeTaxRate: 3.05,
    incomeTaxNote: "flat rate of 3.05%",
  },
  {
    slug: "iowa",
    name: "Iowa",
    abbreviation: "IA",
    hasIncomeTax: true,
    incomeTaxRate: 5.7,
    incomeTaxNote: "flat rate of 5.7%",
  },
  {
    slug: "kansas",
    name: "Kansas",
    abbreviation: "KS",
    hasIncomeTax: true,
    incomeTaxRate: 5.7,
    incomeTaxNote: "progressive 3.1%-5.7%",
  },
  {
    slug: "kentucky",
    name: "Kentucky",
    abbreviation: "KY",
    hasIncomeTax: true,
    incomeTaxRate: 4.5,
    incomeTaxNote: "flat rate of 4.5%",
  },
  {
    slug: "louisiana",
    name: "Louisiana",
    abbreviation: "LA",
    hasIncomeTax: true,
    incomeTaxRate: 4.25,
    incomeTaxNote: "progressive 1.85%-4.25%",
  },
  {
    slug: "maine",
    name: "Maine",
    abbreviation: "ME",
    hasIncomeTax: true,
    incomeTaxRate: 7.15,
    incomeTaxNote: "progressive 5.8%-7.15%",
  },
  {
    slug: "maryland",
    name: "Maryland",
    abbreviation: "MD",
    hasIncomeTax: true,
    incomeTaxRate: 5.75,
    incomeTaxNote: "progressive 2%-5.75%",
  },
  {
    slug: "massachusetts",
    name: "Massachusetts",
    abbreviation: "MA",
    hasIncomeTax: true,
    incomeTaxRate: 5.0,
    incomeTaxNote: "flat rate of 5%",
  },
  {
    slug: "michigan",
    name: "Michigan",
    abbreviation: "MI",
    hasIncomeTax: true,
    incomeTaxRate: 4.25,
    incomeTaxNote: "flat rate of 4.25%",
  },
  {
    slug: "minnesota",
    name: "Minnesota",
    abbreviation: "MN",
    hasIncomeTax: true,
    incomeTaxRate: 9.85,
    incomeTaxNote: "progressive 5.35%-9.85%",
  },
  {
    slug: "mississippi",
    name: "Mississippi",
    abbreviation: "MS",
    hasIncomeTax: true,
    incomeTaxRate: 5.0,
    incomeTaxNote: "flat rate of 5%",
  },
  {
    slug: "missouri",
    name: "Missouri",
    abbreviation: "MO",
    hasIncomeTax: true,
    incomeTaxRate: 4.95,
    incomeTaxNote: "progressive 1.5%-4.95%",
  },
  {
    slug: "montana",
    name: "Montana",
    abbreviation: "MT",
    hasIncomeTax: true,
    incomeTaxRate: 5.9,
    incomeTaxNote: "progressive 4.7%-5.9%",
  },
  {
    slug: "nebraska",
    name: "Nebraska",
    abbreviation: "NE",
    hasIncomeTax: true,
    incomeTaxRate: 6.64,
    incomeTaxNote: "progressive 2.46%-6.64%",
  },
  {
    slug: "nevada",
    name: "Nevada",
    abbreviation: "NV",
    hasIncomeTax: false,
    incomeTaxRate: 0,
    incomeTaxNote: "no state income tax",
  },
  {
    slug: "new-hampshire",
    name: "New Hampshire",
    abbreviation: "NH",
    hasIncomeTax: false,
    incomeTaxRate: 0,
    incomeTaxNote: "no income tax on wages (only dividends/interest)",
  },
  {
    slug: "new-jersey",
    name: "New Jersey",
    abbreviation: "NJ",
    hasIncomeTax: true,
    incomeTaxRate: 10.75,
    incomeTaxNote: "progressive 1.4%-10.75%",
  },
  {
    slug: "new-mexico",
    name: "New Mexico",
    abbreviation: "NM",
    hasIncomeTax: true,
    incomeTaxRate: 5.9,
    incomeTaxNote: "progressive 1.7%-5.9%",
  },
  {
    slug: "new-york",
    name: "New York",
    abbreviation: "NY",
    hasIncomeTax: true,
    incomeTaxRate: 10.9,
    incomeTaxNote: "progressive 4%-10.9%",
  },
  {
    slug: "north-carolina",
    name: "North Carolina",
    abbreviation: "NC",
    hasIncomeTax: true,
    incomeTaxRate: 4.5,
    incomeTaxNote: "flat rate of 4.5%",
  },
  {
    slug: "north-dakota",
    name: "North Dakota",
    abbreviation: "ND",
    hasIncomeTax: true,
    incomeTaxRate: 2.5,
    incomeTaxNote: "progressive 1.1%-2.5%",
  },
  {
    slug: "ohio",
    name: "Ohio",
    abbreviation: "OH",
    hasIncomeTax: true,
    incomeTaxRate: 3.5,
    incomeTaxNote: "progressive 2.75%-3.5%",
  },
  {
    slug: "oklahoma",
    name: "Oklahoma",
    abbreviation: "OK",
    hasIncomeTax: true,
    incomeTaxRate: 4.75,
    incomeTaxNote: "progressive 0.25%-4.75%",
  },
  {
    slug: "oregon",
    name: "Oregon",
    abbreviation: "OR",
    hasIncomeTax: true,
    incomeTaxRate: 9.9,
    incomeTaxNote: "progressive 4.75%-9.9%",
  },
  {
    slug: "pennsylvania",
    name: "Pennsylvania",
    abbreviation: "PA",
    hasIncomeTax: true,
    incomeTaxRate: 3.07,
    incomeTaxNote: "flat rate of 3.07%",
  },
  {
    slug: "rhode-island",
    name: "Rhode Island",
    abbreviation: "RI",
    hasIncomeTax: true,
    incomeTaxRate: 5.99,
    incomeTaxNote: "progressive 3.75%-5.99%",
  },
  {
    slug: "south-carolina",
    name: "South Carolina",
    abbreviation: "SC",
    hasIncomeTax: true,
    incomeTaxRate: 6.4,
    incomeTaxNote: "progressive 0%-6.4%",
  },
  {
    slug: "south-dakota",
    name: "South Dakota",
    abbreviation: "SD",
    hasIncomeTax: false,
    incomeTaxRate: 0,
    incomeTaxNote: "no state income tax",
  },
  {
    slug: "tennessee",
    name: "Tennessee",
    abbreviation: "TN",
    hasIncomeTax: false,
    incomeTaxRate: 0,
    incomeTaxNote: "no state income tax",
  },
  {
    slug: "texas",
    name: "Texas",
    abbreviation: "TX",
    hasIncomeTax: false,
    incomeTaxRate: 0,
    incomeTaxNote: "no state income tax",
  },
  {
    slug: "utah",
    name: "Utah",
    abbreviation: "UT",
    hasIncomeTax: true,
    incomeTaxRate: 4.55,
    incomeTaxNote: "flat rate of 4.55%",
  },
  {
    slug: "vermont",
    name: "Vermont",
    abbreviation: "VT",
    hasIncomeTax: true,
    incomeTaxRate: 8.75,
    incomeTaxNote: "progressive 3.35%-8.75%",
  },
  {
    slug: "virginia",
    name: "Virginia",
    abbreviation: "VA",
    hasIncomeTax: true,
    incomeTaxRate: 5.75,
    incomeTaxNote: "progressive 2%-5.75%",
  },
  {
    slug: "washington",
    name: "Washington",
    abbreviation: "WA",
    hasIncomeTax: false,
    incomeTaxRate: 0,
    incomeTaxNote: "no state income tax",
  },
  {
    slug: "west-virginia",
    name: "West Virginia",
    abbreviation: "WV",
    hasIncomeTax: true,
    incomeTaxRate: 5.12,
    incomeTaxNote: "progressive 2.36%-5.12%",
  },
  {
    slug: "wisconsin",
    name: "Wisconsin",
    abbreviation: "WI",
    hasIncomeTax: true,
    incomeTaxRate: 7.65,
    incomeTaxNote: "progressive 3.5%-7.65%",
  },
  {
    slug: "wyoming",
    name: "Wyoming",
    abbreviation: "WY",
    hasIncomeTax: false,
    incomeTaxRate: 0,
    incomeTaxNote: "no state income tax",
  },
];
